server:
  port: 8083

spring:
  application:
    name: stock-service

  rabbitmq:
    host: rabbitmq.tericcabrel.com
    port: 5671
    username: admin
    password: MyStrong-P4ssw0rd$
    virtual-host: mbmseyiz
    ssl:
      enabled: true
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
    publisher-confirm-type: correlated
    publisher-returns: true

  datasource:
    url: jdbc:mysql://localhost:3306/stockdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
