server:
  port: 8082

spring:
  application:
    name: payment-service

  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5671
    username: mbmseyiz
    password: jKz6Xz1a3SFnjO5HMVURWMvPCRSeZOZz
    virtual-host: mbmseyiz
    ssl:
      enabled: true
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
    publisher-confirm-type: correlated
    publisher-returns: true

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root 
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update 
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
