server:
  port: 8081

spring:
  application:
    name: order-service

  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5671
    username: mbmseyiz
    password: jKz6Xz1a3SFnjO5HMVURWMvPCRSeZOZz
    virtual-host: mbmseyiz
    ssl:
      enabled: true
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
    publisher-confirm-type: correlated
    publisher-returns: true

  management:
    endpoints:
      web:
        exposure:
          include: beans

  datasource:
    url: jdbc:mysql://localhost:3306/root # Substitua pelo nome do seu banco de dados
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # Substitua pelo usuário do MySQL
    password:  12345678 # Substitua pela senha do MySQL

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Use 'update' apenas para desenvolvimento
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
